// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using MySql.Data.EntityFrameworkCore.Storage.Internal;
using RecycleProject;
using RecycleProject.Enums.Model;
using System;

namespace RecycleProject.Migrations.Recycle
{
    [DbContext(typeof(RecycleContext))]
    [Migration("20180426183455_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011");

            modelBuilder.Entity("RecycleProject.Model.Entity.AddressEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("City");

                    b.Property<string>("Country");

                    b.Property<string>("Home");

                    b.Property<string>("Index");

                    b.Property<string>("Region");

                    b.Property<string>("Street");

                    b.HasKey("Id");

                    b.ToTable("address");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.CategoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("category");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ContactId");

                    b.Property<string>("Description");

                    b.Property<string>("Name");

                    b.Property<string>("UserId")
                        .HasMaxLength(85);

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("UserId");

                    b.ToTable("company");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.ContactEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AddressId");

                    b.Property<string>("Email");

                    b.Property<string>("Phone");

                    b.Property<string>("Web");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.ToTable("contact");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.LocationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.HasKey("Id");

                    b.ToTable("location");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.PointCategoryRelationship", b =>
                {
                    b.Property<int>("RecyclePointId");

                    b.Property<int>("CategoryId");

                    b.HasKey("RecyclePointId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("relationship");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.RecyclePointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("CompanyId");

                    b.Property<int?>("LocationId");

                    b.Property<int>("WorkDays");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("LocationId");

                    b.ToTable("recyclepoint");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.CompanyEntity", b =>
                {
                    b.HasOne("RecycleProject.Model.Entity.ContactEntity", "Contact")
                        .WithMany()
                        .HasForeignKey("ContactId");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.ContactEntity", b =>
                {
                    b.HasOne("RecycleProject.Model.Entity.AddressEntity", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId");
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.PointCategoryRelationship", b =>
                {
                    b.HasOne("RecycleProject.Model.Entity.CategoryEntity", "Category")
                        .WithMany("Rels")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("RecycleProject.Model.Entity.RecyclePointEntity", "RecyclePoint")
                        .WithMany("Rels")
                        .HasForeignKey("RecyclePointId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("RecycleProject.Model.Entity.RecyclePointEntity", b =>
                {
                    b.HasOne("RecycleProject.Model.Entity.CompanyEntity", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId");

                    b.HasOne("RecycleProject.Model.Entity.LocationEntity", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");
                });
#pragma warning restore 612, 618
        }
    }
}
